"use strict";
/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g = Object.create((typeof Iterator === "function" ? Iterator : Object).prototype);
    return g.next = verb(0), g["throw"] = verb(1), g["return"] = verb(2), typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (g && (g = 0, op[0] && (_ = 0)), _) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.CLAIM_GRADUATION_DISCRIMINATOR = void 0;
exports.getClaimGraduationDiscriminatorBytes = getClaimGraduationDiscriminatorBytes;
exports.getClaimGraduationInstructionDataEncoder = getClaimGraduationInstructionDataEncoder;
exports.getClaimGraduationInstructionDataDecoder = getClaimGraduationInstructionDataDecoder;
exports.getClaimGraduationInstructionDataCodec = getClaimGraduationInstructionDataCodec;
exports.getClaimGraduationInstructionAsync = getClaimGraduationInstructionAsync;
exports.getClaimGraduationInstruction = getClaimGraduationInstruction;
exports.parseClaimGraduationInstruction = parseClaimGraduationInstruction;
var gill_1 = require("gill");
var programs_1 = require("../programs");
var shared_1 = require("../shared");
exports.CLAIM_GRADUATION_DISCRIMINATOR = new Uint8Array([
    87, 121, 87, 168, 63, 70, 91, 158,
]);
function getClaimGraduationDiscriminatorBytes() {
    return (0, gill_1.fixEncoderSize)((0, gill_1.getBytesEncoder)(), 8).encode(exports.CLAIM_GRADUATION_DISCRIMINATOR);
}
function getClaimGraduationInstructionDataEncoder() {
    return (0, gill_1.transformEncoder)((0, gill_1.getStructEncoder)([
        ['discriminator', (0, gill_1.fixEncoderSize)((0, gill_1.getBytesEncoder)(), 8)],
        [
            'requiredCourses',
            (0, gill_1.getArrayEncoder)((0, gill_1.addEncoderSizePrefix)((0, gill_1.getUtf8Encoder)(), (0, gill_1.getU32Encoder)())),
        ],
    ]), function (value) { return (__assign(__assign({}, value), { discriminator: exports.CLAIM_GRADUATION_DISCRIMINATOR })); });
}
function getClaimGraduationInstructionDataDecoder() {
    return (0, gill_1.getStructDecoder)([
        ['discriminator', (0, gill_1.fixDecoderSize)((0, gill_1.getBytesDecoder)(), 8)],
        [
            'requiredCourses',
            (0, gill_1.getArrayDecoder)((0, gill_1.addDecoderSizePrefix)((0, gill_1.getUtf8Decoder)(), (0, gill_1.getU32Decoder)())),
        ],
    ]);
}
function getClaimGraduationInstructionDataCodec() {
    return (0, gill_1.combineCodec)(getClaimGraduationInstructionDataEncoder(), getClaimGraduationInstructionDataDecoder());
}
function getClaimGraduationInstructionAsync(input, config) {
    return __awaiter(this, void 0, void 0, function () {
        var programAddress, originalAccounts, accounts, args, _a, _b, getAccountMeta;
        var _c, _d, _e, _f, _g;
        return __generator(this, function (_h) {
            switch (_h.label) {
                case 0:
                    programAddress = (_c = config === null || config === void 0 ? void 0 : config.programAddress) !== null && _c !== void 0 ? _c : programs_1.ACADEMIC_CHAIN_PROGRAM_ADDRESS;
                    originalAccounts = {
                        student: { value: (_d = input.student) !== null && _d !== void 0 ? _d : null, isWritable: true },
                        studentProfile: { value: (_e = input.studentProfile) !== null && _e !== void 0 ? _e : null, isWritable: true },
                        graduationMint: { value: (_f = input.graduationMint) !== null && _f !== void 0 ? _f : null, isWritable: true },
                        systemProgram: { value: (_g = input.systemProgram) !== null && _g !== void 0 ? _g : null, isWritable: false },
                    };
                    accounts = originalAccounts;
                    args = __assign({}, input);
                    if (!!accounts.studentProfile.value) return [3 /*break*/, 2];
                    _a = accounts.studentProfile;
                    return [4 /*yield*/, (0, gill_1.getProgramDerivedAddress)({
                            programAddress: programAddress,
                            seeds: [
                                (0, gill_1.getBytesEncoder)().encode(new Uint8Array([
                                    115, 116, 117, 100, 101, 110, 116, 95, 112, 114, 111, 102, 105, 108,
                                    101,
                                ])),
                                (0, gill_1.getAddressEncoder)().encode((0, shared_1.expectAddress)(accounts.student.value)),
                            ],
                        })];
                case 1:
                    _a.value = _h.sent();
                    _h.label = 2;
                case 2:
                    if (!!accounts.graduationMint.value) return [3 /*break*/, 4];
                    _b = accounts.graduationMint;
                    return [4 /*yield*/, (0, gill_1.getProgramDerivedAddress)({
                            programAddress: programAddress,
                            seeds: [
                                (0, gill_1.getBytesEncoder)().encode(new Uint8Array([
                                    103, 114, 97, 100, 117, 97, 116, 105, 111, 110, 95, 109, 105, 110,
                                    116,
                                ])),
                                (0, gill_1.getAddressEncoder)().encode((0, shared_1.expectAddress)(accounts.student.value)),
                            ],
                        })];
                case 3:
                    _b.value = _h.sent();
                    _h.label = 4;
                case 4:
                    if (!accounts.systemProgram.value) {
                        accounts.systemProgram.value =
                            '11111111111111111111111111111111';
                    }
                    getAccountMeta = (0, shared_1.getAccountMetaFactory)(programAddress, 'programId');
                    return [2 /*return*/, Object.freeze({
                            accounts: [
                                getAccountMeta(accounts.student),
                                getAccountMeta(accounts.studentProfile),
                                getAccountMeta(accounts.graduationMint),
                                getAccountMeta(accounts.systemProgram),
                            ],
                            data: getClaimGraduationInstructionDataEncoder().encode(args),
                            programAddress: programAddress,
                        })];
            }
        });
    });
}
function getClaimGraduationInstruction(input, config) {
    var _a, _b, _c, _d, _e;
    // Program address.
    var programAddress = (_a = config === null || config === void 0 ? void 0 : config.programAddress) !== null && _a !== void 0 ? _a : programs_1.ACADEMIC_CHAIN_PROGRAM_ADDRESS;
    // Original accounts.
    var originalAccounts = {
        student: { value: (_b = input.student) !== null && _b !== void 0 ? _b : null, isWritable: true },
        studentProfile: { value: (_c = input.studentProfile) !== null && _c !== void 0 ? _c : null, isWritable: true },
        graduationMint: { value: (_d = input.graduationMint) !== null && _d !== void 0 ? _d : null, isWritable: true },
        systemProgram: { value: (_e = input.systemProgram) !== null && _e !== void 0 ? _e : null, isWritable: false },
    };
    var accounts = originalAccounts;
    // Original args.
    var args = __assign({}, input);
    // Resolve default values.
    if (!accounts.systemProgram.value) {
        accounts.systemProgram.value =
            '11111111111111111111111111111111';
    }
    var getAccountMeta = (0, shared_1.getAccountMetaFactory)(programAddress, 'programId');
    return Object.freeze({
        accounts: [
            getAccountMeta(accounts.student),
            getAccountMeta(accounts.studentProfile),
            getAccountMeta(accounts.graduationMint),
            getAccountMeta(accounts.systemProgram),
        ],
        data: getClaimGraduationInstructionDataEncoder().encode(args),
        programAddress: programAddress,
    });
}
function parseClaimGraduationInstruction(instruction) {
    if (instruction.accounts.length < 4) {
        // TODO: Coded error.
        throw new Error('Not enough accounts');
    }
    var accountIndex = 0;
    var getNextAccount = function () {
        var accountMeta = instruction.accounts[accountIndex];
        accountIndex += 1;
        return accountMeta;
    };
    return {
        programAddress: instruction.programAddress,
        accounts: {
            student: getNextAccount(),
            studentProfile: getNextAccount(),
            graduationMint: getNextAccount(),
            systemProgram: getNextAccount(),
        },
        data: getClaimGraduationInstructionDataDecoder().decode(instruction.data),
    };
}
