/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from 'gill';
import { ACADEMIC_CHAIN_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  expectSome,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const REGISTER_COURSE_DISCRIMINATOR = new Uint8Array([
  254, 131, 130, 70, 100, 68, 139, 121,
]);

export function getRegisterCourseDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    REGISTER_COURSE_DISCRIMINATOR
  );
}

export type RegisterCourseInstruction<
  TProgram extends string = typeof ACADEMIC_CHAIN_PROGRAM_ADDRESS,
  TAccountStudent extends string | AccountMeta<string> = string,
  TAccountCourse extends string | AccountMeta<string> = string,
  TAccountEnrollment extends string | AccountMeta<string> = string,
  TAccountStudentProfile extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountCreditMint extends string | AccountMeta<string> = string,
  TAccountStudentCreditAccount extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountStudent extends string
        ? WritableSignerAccount<TAccountStudent> &
            AccountSignerMeta<TAccountStudent>
        : TAccountStudent,
      TAccountCourse extends string
        ? ReadonlyAccount<TAccountCourse>
        : TAccountCourse,
      TAccountEnrollment extends string
        ? WritableAccount<TAccountEnrollment>
        : TAccountEnrollment,
      TAccountStudentProfile extends string
        ? WritableAccount<TAccountStudentProfile>
        : TAccountStudentProfile,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountCreditMint extends string
        ? WritableAccount<TAccountCreditMint>
        : TAccountCreditMint,
      TAccountStudentCreditAccount extends string
        ? WritableAccount<TAccountStudentCreditAccount>
        : TAccountStudentCreditAccount,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type RegisterCourseInstructionData = {
  discriminator: ReadonlyUint8Array;
  courseId: string;
};

export type RegisterCourseInstructionDataArgs = { courseId: string };

export function getRegisterCourseInstructionDataEncoder(): Encoder<RegisterCourseInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['courseId', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ]),
    (value) => ({ ...value, discriminator: REGISTER_COURSE_DISCRIMINATOR })
  );
}

export function getRegisterCourseInstructionDataDecoder(): Decoder<RegisterCourseInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['courseId', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getRegisterCourseInstructionDataCodec(): Codec<
  RegisterCourseInstructionDataArgs,
  RegisterCourseInstructionData
> {
  return combineCodec(
    getRegisterCourseInstructionDataEncoder(),
    getRegisterCourseInstructionDataDecoder()
  );
}

export type RegisterCourseAsyncInput<
  TAccountStudent extends string = string,
  TAccountCourse extends string = string,
  TAccountEnrollment extends string = string,
  TAccountStudentProfile extends string = string,
  TAccountConfig extends string = string,
  TAccountCreditMint extends string = string,
  TAccountStudentCreditAccount extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  student: TransactionSigner<TAccountStudent>;
  course?: Address<TAccountCourse>;
  enrollment?: Address<TAccountEnrollment>;
  studentProfile?: Address<TAccountStudentProfile>;
  config?: Address<TAccountConfig>;
  creditMint: Address<TAccountCreditMint>;
  studentCreditAccount?: Address<TAccountStudentCreditAccount>;
  tokenProgram?: Address<TAccountTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  courseId: RegisterCourseInstructionDataArgs['courseId'];
};

export async function getRegisterCourseInstructionAsync<
  TAccountStudent extends string,
  TAccountCourse extends string,
  TAccountEnrollment extends string,
  TAccountStudentProfile extends string,
  TAccountConfig extends string,
  TAccountCreditMint extends string,
  TAccountStudentCreditAccount extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ACADEMIC_CHAIN_PROGRAM_ADDRESS,
>(
  input: RegisterCourseAsyncInput<
    TAccountStudent,
    TAccountCourse,
    TAccountEnrollment,
    TAccountStudentProfile,
    TAccountConfig,
    TAccountCreditMint,
    TAccountStudentCreditAccount,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  RegisterCourseInstruction<
    TProgramAddress,
    TAccountStudent,
    TAccountCourse,
    TAccountEnrollment,
    TAccountStudentProfile,
    TAccountConfig,
    TAccountCreditMint,
    TAccountStudentCreditAccount,
    TAccountTokenProgram,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? ACADEMIC_CHAIN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    student: { value: input.student ?? null, isWritable: true },
    course: { value: input.course ?? null, isWritable: false },
    enrollment: { value: input.enrollment ?? null, isWritable: true },
    studentProfile: { value: input.studentProfile ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    creditMint: { value: input.creditMint ?? null, isWritable: true },
    studentCreditAccount: {
      value: input.studentCreditAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.course.value) {
    accounts.course.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([99, 111, 117, 114, 115, 101])),
        addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder()).encode(
          expectSome(args.courseId)
        ),
      ],
    });
  }
  if (!accounts.enrollment.value) {
    accounts.enrollment.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([101, 110, 114, 111, 108, 108, 109, 101, 110, 116])
        ),
        getAddressEncoder().encode(expectAddress(accounts.student.value)),
        addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder()).encode(
          expectSome(args.courseId)
        ),
      ],
    });
  }
  if (!accounts.studentProfile.value) {
    accounts.studentProfile.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            115, 116, 117, 100, 101, 110, 116, 95, 112, 114, 111, 102, 105, 108,
            101,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.student.value)),
      ],
    });
  }
  if (!accounts.config.value) {
    accounts.config.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([99, 111, 110, 102, 105, 103])),
      ],
    });
  }
  if (!accounts.studentCreditAccount.value) {
    accounts.studentCreditAccount.value = await getProgramDerivedAddress({
      programAddress:
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.student.value)),
        getBytesEncoder().encode(
          new Uint8Array([
            6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235,
            121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133,
            126, 255, 0, 169,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.creditMint.value)),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.student),
      getAccountMeta(accounts.course),
      getAccountMeta(accounts.enrollment),
      getAccountMeta(accounts.studentProfile),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.creditMint),
      getAccountMeta(accounts.studentCreditAccount),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getRegisterCourseInstructionDataEncoder().encode(
      args as RegisterCourseInstructionDataArgs
    ),
    programAddress,
  } as RegisterCourseInstruction<
    TProgramAddress,
    TAccountStudent,
    TAccountCourse,
    TAccountEnrollment,
    TAccountStudentProfile,
    TAccountConfig,
    TAccountCreditMint,
    TAccountStudentCreditAccount,
    TAccountTokenProgram,
    TAccountSystemProgram
  >);
}

export type RegisterCourseInput<
  TAccountStudent extends string = string,
  TAccountCourse extends string = string,
  TAccountEnrollment extends string = string,
  TAccountStudentProfile extends string = string,
  TAccountConfig extends string = string,
  TAccountCreditMint extends string = string,
  TAccountStudentCreditAccount extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  student: TransactionSigner<TAccountStudent>;
  course: Address<TAccountCourse>;
  enrollment: Address<TAccountEnrollment>;
  studentProfile: Address<TAccountStudentProfile>;
  config: Address<TAccountConfig>;
  creditMint: Address<TAccountCreditMint>;
  studentCreditAccount: Address<TAccountStudentCreditAccount>;
  tokenProgram?: Address<TAccountTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  courseId: RegisterCourseInstructionDataArgs['courseId'];
};

export function getRegisterCourseInstruction<
  TAccountStudent extends string,
  TAccountCourse extends string,
  TAccountEnrollment extends string,
  TAccountStudentProfile extends string,
  TAccountConfig extends string,
  TAccountCreditMint extends string,
  TAccountStudentCreditAccount extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ACADEMIC_CHAIN_PROGRAM_ADDRESS,
>(
  input: RegisterCourseInput<
    TAccountStudent,
    TAccountCourse,
    TAccountEnrollment,
    TAccountStudentProfile,
    TAccountConfig,
    TAccountCreditMint,
    TAccountStudentCreditAccount,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): RegisterCourseInstruction<
  TProgramAddress,
  TAccountStudent,
  TAccountCourse,
  TAccountEnrollment,
  TAccountStudentProfile,
  TAccountConfig,
  TAccountCreditMint,
  TAccountStudentCreditAccount,
  TAccountTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? ACADEMIC_CHAIN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    student: { value: input.student ?? null, isWritable: true },
    course: { value: input.course ?? null, isWritable: false },
    enrollment: { value: input.enrollment ?? null, isWritable: true },
    studentProfile: { value: input.studentProfile ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    creditMint: { value: input.creditMint ?? null, isWritable: true },
    studentCreditAccount: {
      value: input.studentCreditAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.student),
      getAccountMeta(accounts.course),
      getAccountMeta(accounts.enrollment),
      getAccountMeta(accounts.studentProfile),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.creditMint),
      getAccountMeta(accounts.studentCreditAccount),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getRegisterCourseInstructionDataEncoder().encode(
      args as RegisterCourseInstructionDataArgs
    ),
    programAddress,
  } as RegisterCourseInstruction<
    TProgramAddress,
    TAccountStudent,
    TAccountCourse,
    TAccountEnrollment,
    TAccountStudentProfile,
    TAccountConfig,
    TAccountCreditMint,
    TAccountStudentCreditAccount,
    TAccountTokenProgram,
    TAccountSystemProgram
  >);
}

export type ParsedRegisterCourseInstruction<
  TProgram extends string = typeof ACADEMIC_CHAIN_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    student: TAccountMetas[0];
    course: TAccountMetas[1];
    enrollment: TAccountMetas[2];
    studentProfile: TAccountMetas[3];
    config: TAccountMetas[4];
    creditMint: TAccountMetas[5];
    studentCreditAccount: TAccountMetas[6];
    tokenProgram: TAccountMetas[7];
    systemProgram: TAccountMetas[8];
  };
  data: RegisterCourseInstructionData;
};

export function parseRegisterCourseInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedRegisterCourseInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 9) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      student: getNextAccount(),
      course: getNextAccount(),
      enrollment: getNextAccount(),
      studentProfile: getNextAccount(),
      config: getNextAccount(),
      creditMint: getNextAccount(),
      studentCreditAccount: getNextAccount(),
      tokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getRegisterCourseInstructionDataDecoder().decode(instruction.data),
  };
}
